name: Broken Link Checker


on: 
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Check for Broken Links
      uses: tcort/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        folder-path: 'guides, quickstart, api-reference, sdks'
        file-extension: '.mdx'